import puppeteer from 'puppeteer';
import assert from 'node:assert/strict';
import {spawn} from 'node:child_process';
import {mkdtemp,mkdir,rm} from 'node:fs/promises';
import {existsSync} from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {setTimeout as delay} from 'node:timers/promises';

const data=await mkdtemp(path.join(os.tmpdir(),'monki-decor-'));
const output=process.env.MONKI_ARTIFACT_DIR||path.join(data,'screens');await mkdir(output,{recursive:true});
const port=59000+Math.floor(Math.random()*1500),base=`http://127.0.0.1:${port}`;
const server=spawn(process.execPath,['server.mjs'],{cwd:new URL('..',import.meta.url),env:{...process.env,PORT:String(port),HOST:'127.0.0.1',MONKI_DATA_DIR:data},stdio:'ignore'});
let browser,page;const errors=[];
const state=()=>page.evaluate(()=>JSON.parse(localStorage.getItem('monki-world-sandbox-v1')).world);
const shot=name=>page.screenshot({path:path.join(output,name),fullPage:false});
const press=text=>page.evaluate(text=>{const b=[...document.querySelectorAll('#decor-editor button')].find(b=>b.textContent.trim()===text);if(!b)throw Error(`Missing ${text}`);b.click();},text);
const click=selector=>page.evaluate(selector=>{const node=document.querySelector(selector);if(!node)throw Error(`Missing ${selector}`);node.click();},selector);
const tapScene=async(x,y)=>{const p=await page.evaluate(({x,y})=>decorScene.screenPoint({x,y}),{x,y});await page.mouse.click(p.x,p.y);};
const captureScene=()=>page.evaluate(async()=>{const {Scene}=await import('./scene.js'),draw=Scene.prototype.draw;Scene.prototype.draw=function(time){window.decorScene=this;return draw.call(this,time);};});
try{
  let healthy=false;for(let i=0;i<80;i++){try{if((await fetch(base+'/api/health')).ok){healthy=true;break;}}catch{}await delay(60);}assert.ok(healthy);
  const chrome='/Applications/Google Chrome.app/Contents/MacOS/Google Chrome';
  browser=await puppeteer.launch({executablePath:process.env.BROWSER_BIN||(existsSync(chrome)?chrome:puppeteer.executablePath()),headless:true,args:['--no-sandbox']});
  page=await browser.newPage();page.on('pageerror',error=>errors.push(error.message));
  await page.setViewport({width:390,height:844,deviceScaleFactor:2});await page.goto(base+'/?test=1',{waitUntil:'networkidle0'});
  assert.deepEqual((await state()).objects.map(o=>o.type),['couch','lamp','bowl']);
  if(await page.$eval('#sheet',e=>e.open))await page.click('#close-sheet');
  await shot('new-world-phone.png');
  await page.click('#open-tools');await page.click('#decorate');
  assert.equal(await page.$('[aria-label="Place House plant"]'),null,'The unearned plant should not already be on the tray');
  await press('Surfaces');assert.equal(await page.$('[aria-label="Walls: Butter"]'),null,'Later wall choices should wait for adventures');
  await press('Done');
  await page.evaluate(async()=>{const key='monki-world-sandbox-v1',save=JSON.parse(localStorage.getItem(key)),{applyOperation}=await import('./shared/world.js');save.world=applyOperation(save.world,{id:'first-decor-reward',actor:save.actor,type:'adventureComplete',chapter:'up',index:0},Date.now());localStorage.setItem(key,JSON.stringify(save));});
  await page.reload({waitUntil:'networkidle0'});if(await page.$eval('#sheet',e=>e.open))await page.click('#close-sheet');
  assert.ok(await page.$('#open-tools.new-decor'),'An adventure unlock stays findable until the editor is viewed');
  await shot('first-adventure-unlock-phone.png');
  await page.click('#open-tools');assert.match(await page.$eval('#decorate',e=>e.textContent),/new/);await page.click('#decorate');
  await shot('first-adventure-unlock-editor.png');
  assert.equal(await page.$eval('.decor-editor-rail .decor-editor-card:first-child',e=>e.getAttribute('aria-label')),'Place House plant','New furniture must lead the tray');
  assert.match(await page.$eval('.decor-editor-rail .decor-editor-card:first-child',e=>e.textContent),/new/);
  await press('Surfaces');assert.ok(await page.$('[aria-label="Walls: Butter"]'));
  await press('Done');assert.equal(await page.$('#open-tools.new-decor'),null,'The marker clears after seeing the choices');
  await page.evaluate(()=>{const key='monki-world-sandbox-v1',save=JSON.parse(localStorage.getItem(key));save.world.completed=24;localStorage.setItem(key,JSON.stringify(save));});
  await page.reload({waitUntil:'networkidle0'});await page.click('#close-sheet');
  await captureScene();await delay(40);
  await page.click('#open-tools');await page.click('#decorate');
  assert.equal(await page.$eval('#decor-editor',e=>e.hidden),false);
  assert.equal(await page.$eval('#sheet',e=>e.open),false,'The room must remain visible while decorating');
  const artwork=await page.evaluate(async()=>{const {FURNITURE}=await import('./shared/decor.js'),{furniturePreview}=await import('./furniture-art.js');return Object.keys(FURNITURE).map(id=>{const canvas=furniturePreview(id),pixels=canvas.getContext('2d').getImageData(0,0,90,90).data;let ink=0,hash=2166136261;for(let i=0;i<pixels.length;i+=4){if(pixels[i+3])ink++;hash=Math.imul(hash^pixels[i],16777619);hash=Math.imul(hash^pixels[i+3],16777619);}return{id,ink,hash:hash>>>0};});});
  assert.ok(artwork.every(piece=>piece.ink>70));assert.ok(new Set(artwork.map(piece=>piece.hash)).size>=18);
  await press('Surfaces');await press('Walls');await click('[aria-label="Walls: Plum"]');await press('Floor');await click('[aria-label="Floor: Mint tile"]');
  assert.equal((await state()).catalog.styles.house.wall,'plum');assert.equal((await state()).catalog.styles.house.floor,'mint');await shot('live-surfaces-phone.png');
  await press('Add');await click('[aria-label="Moss"]');await click('[aria-label="Place Armchair"]');await tapScene(196,246);
  let world=await state(),chair=world.objects.find(o=>o.type==='armchair');assert.ok(chair);assert.equal(chair.finish,'moss');assert.ok(Math.abs(chair.x-196)<3);await shot('live-furniture-phone.png');
  await press('In place');await page.evaluate(()=>{const b=[...document.querySelectorAll('.decor-editor-card')].find(b=>b.textContent.includes('Armchair'));b.click();});await press('Store');
  assert.equal((await state()).objects.some(o=>o.id===chair.id),false);
  await press('Put away');await page.click('[aria-label="Place stored Armchair"]');await tapScene(257,276);
  world=await state();assert.ok(Math.abs(world.objects.find(o=>o.id===chair.id).x-257)<2);
  await shot('custom-room-phone.png');
  const from=await page.evaluate(()=>decorScene.screenPoint({x:257,y:276})),to=await page.evaluate(()=>decorScene.screenPoint({x:285,y:291}));
  await page.mouse.move(from.x,from.y);await page.mouse.down();await page.mouse.move(to.x,to.y,{steps:12});await page.mouse.up();
  assert.ok((await state()).objects.find(o=>o.id===chair.id).x>270,'Placed furniture should drag naturally');
  await press('Done');
  await page.evaluate(async()=>{const {ambienceAt}=await import('./shared/ambience.js');decorScene.timeOverride=22;decorScene.ambience=ambienceAt(Date.now(),22);decorScene.night=true;document.documentElement.classList.add('night');});await delay(80);await shot('custom-room-night.png');
  await page.click('#open-tools');await page.click('#decorate');await shot('live-editor-night.png');await press('Done');
  await page.evaluate(async()=>{const {ambienceAt}=await import('./shared/ambience.js');decorScene.timeOverride=12;decorScene.ambience=ambienceAt(Date.now(),12);decorScene.night=false;document.documentElement.classList.remove('night');});
  await click('[aria-label="Garden"]');await page.click('#open-tools');await page.click('#decorate');await press('Surfaces');await press('Distance');
  for(const name of ['Hills','Forest','City','Sea','Mountains','Orchard','Open sky']){await click(`[aria-label="Distance: ${name}"]`);await delay(30);await shot(`garden-${name.toLowerCase().replace(' ','-')}.png`);}
  await click('[aria-label="Distance: Mountains"]');await press('Fence');await click('[aria-label="Fence: Blue"]');
  assert.equal((await state()).catalog.styles.garden.backdrop,'mountains');await press('Done');await shot('custom-garden-phone.png');
  await click('[aria-label="Roof"]');await page.click('#open-tools');await page.click('#decorate');await press('Surfaces');await press('Tiles');await click('[aria-label="Tiles: Slate"]');await press('Distance');await click('[aria-label="Distance: City"]');
  assert.equal((await state()).catalog.styles.roof.tile,'slate');await press('Done');await shot('custom-roof-phone.png');
  await click('[aria-label="Down there"]');await page.click('#open-tools');await page.click('#decorate');await press('Surfaces');
  for(const name of ['Stone','Brick','Blue']){await click(`[aria-label="Walls: ${name}"]`);await delay(30);await shot(`cellar-${name.toLowerCase()}.png`);}
  assert.equal((await state()).catalog.styles.cellar.wall,'blue');await press('Done');
  await click('[aria-label="Home"]');
  for(const width of [320,390,768]){await page.setViewport({width,height:844,deviceScaleFactor:2});await delay(80);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth+2),true,`Overflow at ${width}`);await page.click('#open-tools');await page.click('#decorate');await shot(`live-editor-${width}.png`);await press('Done');}
  await page.evaluate(()=>{const key='monki-world-sandbox-v1',save=JSON.parse(localStorage.getItem(key));save.world.decor.push('kite');localStorage.setItem(key,JSON.stringify(save));location.reload();});
  await page.waitForSelector('#world');await captureScene();await delay(70);if(await page.$eval('#sheet',e=>e.open))await page.click('#close-sheet');
  await tapScene(166,112);assert.equal(await page.$eval('#decor-editor',e=>e.hidden),false,'Tapping a keepsake should open its live controls');
  await page.click('.decor-editor-selected .decor-action');
  assert.ok((await state()).catalog.hiddenDecor.includes('kite'));
  await press('Put away');await page.evaluate(()=>{const b=[...document.querySelectorAll('.decor-editor-card')].find(b=>b.textContent.includes('Show kite'));b.click();});
  assert.ok(!(await state()).catalog.hiddenDecor.includes('kite'));
  await press('In place');await page.evaluate(()=>{const b=[...document.querySelectorAll('.decor-editor-card')].find(b=>b.textContent.includes('Armchair'));b.click();});
  await press('Remove');assert.ok((await state()).objects.some(o=>o.id===chair.id));await press('Remove?');assert.ok(!(await state()).objects.some(o=>o.id===chair.id));
  await page.setViewport({width:320,height:680,deviceScaleFactor:2});await press('Add');await click('[aria-label="Place Cactus"]');await shot('live-placement-320.png');await press('Place centre');
  assert.ok((await state()).objects.some(o=>o.type==='cactus'&&o.x===200&&o.y===259));
  // A saved postcard and an unopened partner gift used to become enormous
  // floor overlays. Check both in the actual phone scene, not only in data.
  await page.evaluate(()=>{const key='monki-world-sandbox-v1',save=JSON.parse(localStorage.getItem(key));save.world.moments.unshift({id:'visual-moment',chapter:'up',who:'julia',at:Date.now(),actor:'monki',hat:'cone',title:'A very normal hat.',variant:'plain'});save.world.gifts.push({id:'visual-gift',from:'julia',to:save.actor,item:'flower',at:Date.now(),opened:false});localStorage.setItem(key,JSON.stringify(save));location.reload();});
  await page.waitForSelector('#world');await captureScene();await delay(70);if(await page.$eval('#sheet',e=>e.open))await page.click('#close-sheet');
  await shot('moment-and-gift-320.png');
  const marks=await page.evaluate(()=>{const boxes=decorScene.hitboxes;return{moment:boxes.find(b=>b.id==='moment'),gift:boxes.find(b=>b.id==='visual-gift'),actorIndices:boxes.map((b,i)=>['david','julia','monki','sernik','galgan'].includes(b.id)?i:-1).filter(i=>i>=0),giftIndex:boxes.findIndex(b=>b.id==='visual-gift')};});
  assert.ok(marks.moment&&marks.gift,'Both visual affordances must have touch targets');
  assert.ok(marks.actorIndices.every(index=>marks.giftIndex<index),'Residents must win touches over a nearby gift');
  await tapScene(304,82);assert.equal(await page.$eval('#sheet',e=>e.open),true,'The wall postcard opens Moments');
  await page.click('#close-sheet');await tapScene(marks.gift.x+marks.gift.w/2,marks.gift.y+marks.gift.h/2);
  assert.equal(await page.$eval('#sheet',e=>e.open),true,'The small edge parcel opens its gift');
  await page.click('#close-sheet');
  await page.evaluate(()=>{const key='monki-world-sandbox-v1',save=JSON.parse(localStorage.getItem(key));save.world.completed=144;localStorage.setItem(key,JSON.stringify(save));});
  await page.reload({waitUntil:'networkidle0'});await captureScene();if(await page.$eval('#sheet',e=>e.open))await page.click('#close-sheet');
  await click('[aria-label="Roof"]');await page.click('#open-tools');await page.click('#decorate');await press('Surfaces');await press('Tiles');await click('[aria-label="Tiles: Copper"]');await shot('later-roof-copper.png');await press('Done');
  await click('[aria-label="Garden"]');await page.click('#open-tools');await page.click('#decorate');await press('Surfaces');await press('Ground');await click('[aria-label="Ground: Clover"]');await shot('later-garden-clover.png');await press('Done');
  await click('[aria-label="Home"]');await page.click('#open-tools');await page.click('#decorate');await press('Surfaces');await press('Walls');await click('[aria-label="Walls: Cocoa"]');await shot('later-house-cocoa.png');await press('Done');
  await click('[aria-label="Down there"]');await page.click('#open-tools');await page.click('#decorate');await press('Surfaces');await press('Walls');await click('[aria-label="Walls: Chalk"]');await shot('later-cellar-chalk.png');await press('Done');
  assert.deepEqual(errors,[]);
  console.log(`PASS: live decorating, backgrounds, exact placement, drag, storage, keepsake cleanup and responsive tray. Screenshots: ${output}`);
}finally{await browser?.close();server.kill();await delay(100);await rm(data,{recursive:true,force:true});}
